### ISSUE TITLE
ProtocolMapper default checks

### ISSUE THREAD

**Issue by dasniko** [iteratec/kcwarden#111]
If I understand the `ProtocolMapperWithConfig` monitor properly, I can setup a rule to check if single mappers in the client scopes e.g. write the values to access-token, id-token, userinfo-endpoint, etc., right!? I've not tested this yet, sorry.

A default check of the protocol mappers within the client scopes `profile`, `email`, `phone` and `address` would be good to validate if these mappers do only write their values to the id_token and the userinfo-endpoint, but _not_ to the access_token. Unfortunately, this is a default setting in KC, to write everything to everywhere, which duplicates simply data and leads developers to use tokens not properly.
The data/claims associated with the above-mentioned (OIDC default) scopes, are OIDC standard claims, thus not related to OAuth, thus not related to the access_token. The access_token should actually no user-related data (identity/profile), an identifier (e.g. the `sub` claim) at max.

**Comment by dasniko** [comment]
Meanwhile, I tested the `ProtocolMapperWithConfig` monitor with these settings:

```yaml
- monitor: ProtocolMapperWithConfig
  config:
  - protocol-mapper-type: "oidc-usermodel-[a-z]+-mapper"
    matched-config:
      access.token.claim: 'true'
    allowed: []
    severity: Info
    note: OIDC standard claims should not be contained in the access_token, as the access_token should not contain user profile related data.
```

This gives me findings with protocol mappers which map data to the access_token, as expected, but on the client level, even when these mappers come from a client scope. This way, I get a finding for each mapper in each client.

Instead, I'd like to investigate only the mappers in the client scopes itself and want to get a finding only on client scope level, not on client level. IMHO this makes more sense, as the mappers are configured on the scope itself, not on the client. The client just requests the scope(s). There's no need to have a multiplied finding for each client.

WDYT?
